"""FLEX Program tutorial — in-app deck for onboarding + reference.

Renders the slides exported from assets/flex_tutorial.pptx as a scrollable gallery.
Also offers a one-click download of the source .pptx so anyone can present from it or
update it. Companion document: docs/FLEX_PROGRAM_EXPLAINED.md.

To refresh slides after editing the .pptx:
  1. Replace assets/flex_tutorial.pptx with the new file.
  2. Re-export slides as PNGs into assets/flex_tutorial_slides/ named SlideN.PNG.
     (On Windows with PowerPoint installed, save the deck as "PNG export" via
     File > Export > Change File Type > PNG.)
  3. Commit both the .pptx and the regenerated PNGs.
"""
from __future__ import annotations

from pathlib import Path

import streamlit as st

from core import ui

ui.header(
    "Running FLEX",
    "Tutorial deck for the internal operator's view of the FLEX program — payment, "
    "credit-memo, and invoice mechanics.",
    kicker="Oncura · Tutorial",
)

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"
PPTX_PATH = ASSETS_DIR / "flex_tutorial.pptx"
SLIDES_DIR = ASSETS_DIR / "flex_tutorial_slides"

# ── Download button for the source .pptx ─────────────────────────────────────
dl_col1, dl_col2 = st.columns([3, 1])
dl_col1.caption(
    "The deck is rendered below as a scrollable gallery. For presenting or editing, "
    "download the .pptx — same on-brand color palette and font stack as this app."
)
if PPTX_PATH.exists():
    dl_col2.download_button(
        "Download .pptx",
        data=PPTX_PATH.read_bytes(),
        file_name="flex_tutorial.pptx",
        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        type="primary",
        key="tut_dl_pptx",
    )
else:
    dl_col2.warning("pptx missing")

st.divider()

# ── Slide gallery ────────────────────────────────────────────────────────────
slide_paths = sorted(
    list(SLIDES_DIR.glob("Slide*.PNG")) + list(SLIDES_DIR.glob("Slide*.png")),
    key=lambda p: int("".join(c for c in p.stem if c.isdigit()) or "0"),
)

if not slide_paths:
    st.warning(
        "No slide images found under `assets/flex_tutorial_slides/`. Re-export the deck "
        "as PNGs (one per slide, named `SlideN.PNG`) and commit them. The download "
        "button above still works."
    )
else:
    st.caption(f"{len(slide_paths)} slides — scroll to read or jump via the sidebar buttons.")

    for i, slide in enumerate(slide_paths, start=1):
        with st.container(border=False):
            st.image(str(slide), use_container_width=True)
            st.caption(f"Slide {i} of {len(slide_paths)}")
            st.write("")

st.divider()

# ── Companion materials ──────────────────────────────────────────────────────
st.subheader("Related material")
st.markdown(
    "- **`docs/FLEX_PROGRAM_EXPLAINED.md`** — the source explainer this deck was generated from. "
    "Includes the full brand-system specification so the deck can be regenerated by feeding the "
    "doc back into Claude.\n"
    "- **`docs/RECOVERY.md`** — what to do when the app breaks (Cloud entry-file reset, "
    "AttributeError mid-deploy, etc.).\n"
    "- **`docs/ACCOUNTING_HANDOFF.md`** — manual steps each cycle hands off to accounting "
    "(SaaSAnt uploads, QBO matching, OPD credit-box updates)."
)
