"""FLEX Program tutorial — click-through deck viewer for onboarding + reference.

Displays one slide at a time in a constrained-width window with prev/next navigation.
The .pptx source is downloadable so anyone can present from it or update it.
Companion document: docs/FLEX_PROGRAM_EXPLAINED.md.

To refresh slides after editing the .pptx:
  1. Replace assets/flex_tutorial.pptx with the new file.
  2. Re-export slides as PNGs into assets/flex_tutorial_slides/ named SlideN.PNG.
     (On Windows with PowerPoint installed, save the deck as "PNG export" via
     File > Export > Change File Type > PNG.)
  3. Commit both the .pptx and the regenerated PNGs.
"""
from __future__ import annotations

from pathlib import Path

import streamlit as st

from core import ui

ui.header(
    "Running FLEX",
    "Tutorial deck for the internal operator's view of the FLEX program — payment, "
    "credit-memo, and invoice mechanics.",
    kicker="Oncura · Tutorial",
)

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"
PPTX_PATH = ASSETS_DIR / "flex_tutorial.pptx"
SLIDES_DIR = ASSETS_DIR / "flex_tutorial_slides"

slide_paths = sorted(
    list(SLIDES_DIR.glob("Slide*.PNG")) + list(SLIDES_DIR.glob("Slide*.png")),
    key=lambda p: int("".join(c for c in p.stem if c.isdigit()) or "0"),
)
total = len(slide_paths)

# ── Top toolbar: download + slide jumper ─────────────────────────────────────
tb1, tb2, tb3 = st.columns([2, 2, 1])
tb1.caption(
    "Click through the deck with the arrows below, or jump directly to a slide. "
    "Download the .pptx for presenting or editing."
)
if PPTX_PATH.exists():
    tb3.download_button(
        "Download .pptx",
        data=PPTX_PATH.read_bytes(),
        file_name="flex_tutorial.pptx",
        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        type="primary",
        key="tut_dl_pptx",
        use_container_width=True,
    )

if total == 0:
    st.warning(
        "No slide images found under `assets/flex_tutorial_slides/`. Re-export the deck "
        "as PNGs (one per slide, named `SlideN.PNG`) and commit them."
    )
    st.stop()

# ── State (the selectbox's session_state key is the single source of truth) ──
SS = st.session_state
SS.setdefault("tut_jumper", 0)
SS.tut_jumper = max(0, min(SS.tut_jumper, total - 1))


def _prev():
    SS.tut_jumper = max(0, SS.tut_jumper - 1)


def _next():
    SS.tut_jumper = min(total - 1, SS.tut_jumper + 1)


# Jump-to-slide selector — no `index` arg; Streamlit reads/writes via the key
tb2.selectbox(
    "Jump to slide",
    options=list(range(total)),
    format_func=lambda i: f"Slide {i + 1}",
    key="tut_jumper",
    label_visibility="collapsed",
)

current = SS.tut_jumper

st.divider()

# ── Slide display (constrained width, centered) ──────────────────────────────
_, slide_col, _ = st.columns([1, 4, 1])
with slide_col:
    st.image(str(slide_paths[current]), use_container_width=True)
    st.progress((current + 1) / total)

# ── Bottom nav: prev / indicator / next ──────────────────────────────────────
nav_prev, nav_mid, nav_next = st.columns([1, 4, 1])
nav_prev.button(
    "← Previous",
    key="tut_prev",
    on_click=_prev,
    disabled=(current == 0),
    use_container_width=True,
)
nav_mid.markdown(
    f"<div style='text-align:center; padding-top: 0.4rem; font-family: var(--mono); "
    f"color: var(--muted); letter-spacing: 0.1em;'>"
    f"Slide {current + 1} of {total}</div>",
    unsafe_allow_html=True,
)
nav_next.button(
    "Next →",
    key="tut_next",
    on_click=_next,
    disabled=(current == total - 1),
    use_container_width=True,
    type="primary",
)

st.divider()

# ── Companion materials ──────────────────────────────────────────────────────
with st.expander("Related material"):
    st.markdown(
        "- **`docs/FLEX_PROGRAM_EXPLAINED.md`** — the source explainer this deck was generated from. "
        "Includes the full brand-system specification so the deck can be regenerated by feeding the "
        "doc back into Claude.\n"
        "- **`docs/RECOVERY.md`** — what to do when the app breaks (Cloud entry-file reset, "
        "AttributeError mid-deploy, etc.).\n"
        "- **`docs/ACCOUNTING_HANDOFF.md`** — manual steps each cycle hands off to accounting "
        "(SaasAnt uploads, QBO matching, OPD credit-box updates)."
    )
